//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AddressBook
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Text.RegularExpressions;
    
    public partial class Contact
    {
        public int Id { get; set; }

        [Display(Name = "First Name")]
        [Required(ErrorMessage = "Please provide First Name", AllowEmptyStrings = false)]
        public string FirstName { get; set; }
        [Display(Name = "Last Name")]
        public string LastName { get; set; }
        [Display(Name = "Phone Number")]
        [Required(ErrorMessage = "Please provide Phone Numnber", AllowEmptyStrings = false)]
        [DataType(DataType.PhoneNumber)]
        [RegularExpression(@"^\(?([0-9]{3})\)?[-. ]?([0-9]{3})[-. ]?([0-9]{4})$", ErrorMessage = "Invalid Phone number")]
        public string PhoneNumber
        {
            get
            {
                return this.phoneNumber;
            }
            set
            {
                if (value != null)
                {
                    this.phoneNumber = Regex.Replace(value, @"\s", "");
                }
                else
                    this.phoneNumber = value;
            }

        }
        [Display(Name = "Street Name")]
        [Required(ErrorMessage = "Please provide Street Name", AllowEmptyStrings = false)]
        public string StreetName { get; set; }
        [Display(Name = "City")]
        [Required(ErrorMessage = "Please provide City", AllowEmptyStrings = false)]
        public string City { get; set; }
        [Display(Name = "Province")]
        [Required(ErrorMessage = "Please provide Province", AllowEmptyStrings = false)]
        public string Province { get; set; }
        [Display(Name = "Postal Code")]
        [Required(ErrorMessage = "Please provide Postal Code", AllowEmptyStrings = false)]
        public string PostalCode { get; set; }
        [Display(Name = "Country")]
        [Required(ErrorMessage = "Please provide Country", AllowEmptyStrings = false)]
        public string Country { get; set; }

        
        private string phoneNumber;

    }
}
